USE HeadtripGameServer;

DROP TABLE IF EXISTS Daemons;
GO
CREATE TABLE Daemons (
	DaemonId UNIQUEIDENTIFIER NOT NULL,
	Nickname NVARCHAR(MAX) NOT NULL,
	ServerAddress NVARCHAR(MAX) NOT NULL,
	NumberOfFreeEntries INT NOT NULL DEFAULT 0,
	IsSuperDaemon BIT NOT NULL DEFAULT 0


	CONSTRAINT [PK_Daemons_DaemonId] PRIMARY KEY NONCLUSTERED (DaemonId)
);
GO


